aossie_scholar/urls.py
from django.contrib import admin
from django.urls import path, include
from .router import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('metrics/', include('metrics.urls')),
    path('api/', include(router.urls))
]
 

metrics/fusioncharts/fusioncharts-suite-xt/integrations/django/samples/fusioncharts/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from fusioncharts.views import catalogue

from fusioncharts import datahandler
from fusioncharts.samples import rendering_angular_gauge_using_dictionary_example, rendering_column2d_chart_using_dictionary_example
from fusioncharts.samples import rendering_map_using_dictionary_example, rendering_multiseries_column2d_chart_using_json_example
from fusioncharts.samples import rendering_multiseries_StackedColumn2dline_using_json_example, rendering_pie3d_using_json_example
from fusioncharts.samples import rendering_column_line_area_combi_using_json_example, rendering_map_using_json_example
from fusioncharts.samples import rendering_angular_gauge_using_json_example, client_side_chart_export
from fusioncharts.samples import fetching_json_data_from_url, fetching_xml_data_from_url, fetching_data_from_database
from fusioncharts.samples import drilldown_from_database_example, rendering_charts_by_common_theme
from fusioncharts.samples import export_chart_using_export_handler
from fusioncharts.samples import dynamic_chart_resize, dynamic_chart_type, chart_annotation, chart_update_onclick
from fusioncharts.samples import chart_tooltip, rendering_chart_with_different_language, chart_special_chart
from fusioncharts.samples import product_life_cycle_event, special_event, chart_message, interactive_event, number_format_module
from fusioncharts.samples import special_chart_type_api, chart_instance_level_api, chart_product_level_api
from fusioncharts.samples import updating_chart_properties, highlight_specific_data_points, update_data_runtime
from fusioncharts.samples import get_data_from_scatter_chart
from fusioncharts.samples import Line_Chart_With_Time_Axis, Plotting_Multiple_Series_On_Time_Axis
from fusioncharts.samples import Column_and_line_combination_on_time_axis, Plotting_Two_Variables
from fusioncharts.samples import Different_Plot_Type_Chart, ColumnChart_With_Time_Axis
from fusioncharts.samples import AreaChart_With_Time_Axis, Interactive_candlestick_chart
from fusioncharts.samples import Annotating_single_data_point, Single_Event_Overlay
from fusioncharts.samples import Date_range_event_overlay, Adding_Reference_Line


urlpatterns = [
    url(r'^$', catalogue),
    url(r'^admin/', admin.site.urls),
    url(r'^datahandler', datahandler.getdata),
    url(r'^rendering-angular-gauge-using-dictionary-example', rendering_angular_gauge_using_dictionary_example.chart, name='chart'),
    url(r'^rendering-angular-gauge-using-json-example', rendering_angular_gauge_using_json_example.chart, name='chart'),
    url(r'^rendering-column2d-chart-using-dictionary-example', rendering_column2d_chart_using_dictionary_example.chart, name='chart'),
    url(r'^rendering-map-using-dictionary-example', rendering_map_using_dictionary_example.chart, name='chart'),
    url(r'^rendering-map-using-json-example', rendering_map_using_json_example.chart, name='chart'),
    url(r'^rendering-multiseries-column2d-chart-using-json-example', rendering_multiseries_column2d_chart_using_json_example.chart, name='chart'),
    url(r'^rendering-multiseries-StackedColumn2dline-using-json-example', rendering_multiseries_StackedColumn2dline_using_json_example.chart, name='chart'),
    url(r'^rendering-pie3d-using-json-example', rendering_pie3d_using_json_example.chart, name='chart'),
    url(r'^rendering-column-line-area-combi-using-json-example', rendering_column_line_area_combi_using_json_example.chart, name='chart'),
    url(r'^client-side-chart-export', client_side_chart_export.chart, name='chart'),
    url(r'^fetching-json-data-from-url', fetching_json_data_from_url.chart, name='chart'),
    url(r'^fetching-xml-data-from-url', fetching_xml_data_from_url.chart, name='chart'),
    url(r'^fetching-data-from-database', fetching_data_from_database.chart, name='chart'),
    url(r'^drilldown-from-database-example', drilldown_from_database_example.chart, name='chart'),
    url(r'^rendering-charts-by-common-theme', rendering_charts_by_common_theme.chart, name='chart'),
    url(r'^export-chart-using-export-handler', export_chart_using_export_handler.chart, name='chart'),
    url(r'^dynamic-chart-resize', dynamic_chart_resize.chart, name='chart'),
    url(r'^dynamic-chart-type', dynamic_chart_type.chart, name='chart'),
    url(r'^chart-annotation', chart_annotation.chart, name='chart'),
    url(r'^chart-update-onclick', chart_update_onclick.chart, name='chart'),
    url(r'^rendering-chart-with-different-language', rendering_chart_with_different_language.chart, name='chart'),
    url(r'^chart-special-chart', chart_special_chart.chart, name='chart'),
    url(r'^chart-tooltip', chart_tooltip.chart, name='chart'),
    url(r'^product-life-cycle-event', product_life_cycle_event.chart, name='chart'),
    url(r'^special-event', special_event.chart, name='chart'),
    url(r'^chart-message', chart_message.chart, name='chart'),
    url(r'^interactive-event', interactive_event.chart, name='chart'),
    url(r'^number-format-module', number_format_module.chart, name='chart'),
    url(r'^special-chart-type-api', special_chart_type_api.chart, name='chart'),
    url(r'^chart-instance-level-api', chart_instance_level_api.chart, name='chart'),
    url(r'^chart-product-level-api', chart_product_level_api.chart, name='chart'),
    url(r'^updating-chart-properties', updating_chart_properties.chart, name='chart'),
    url(r'^highlight-specific-data-points', highlight_specific_data_points.chart, name='chart'),
    url(r'^update-data-runtime', update_data_runtime.chart, name='chart'),
    url(r'^get-data-from-scatter-chart', get_data_from_scatter_chart.chart, name='chart'),
    url(r'^Line-Chart-With-Time-Axis', Line_Chart_With_Time_Axis.chart, name='chart'),
    url(r'^Plotting-Multiple-Series-On-Time-Axis', Plotting_Multiple_Series_On_Time_Axis.chart, name='chart'),
    url(r'^Column-and-line-combination-on-time-axis', Column_and_line_combination_on_time_axis.chart, name='chart'),
    url(r'^Plotting-Two-Variables', Plotting_Two_Variables.chart, name='chart'),
    url(r'^Different-Plot-Type-Chart', Different_Plot_Type_Chart.chart, name='chart'),
    url(r'^ColumnChart-With-Time-Axis', ColumnChart_With_Time_Axis.chart, name='chart'),
    url(r'^AreaChart-With-Time-Axis', AreaChart_With_Time_Axis.chart, name='chart'),
    url(r'^Interactive-candlestick-chart', Interactive_candlestick_chart.chart, name='chart'),
    url(r'^Annotating-single-data-point', Annotating_single_data_point.chart, name='chart'),
    url(r'^Single-Event-Overlay', Single_Event_Overlay.chart, name='chart'),
    url(r'^Date-range-event-overlay', Date_range_event_overlay.chart, name='chart'),
    url(r'^Adding-Reference-Line', Adding_Reference_Line.chart, name='chart') 
]

metrics/urls.py
from . import views
from django.urls import path, include

app_name= 'metrics'
urlpatterns = [
path('', views.HomeView.as_view(), name='home'),
path('<str:scholar_url>/results/', views.ResultView.as_view(), name= 'results'),
path('info_page/', views.InfoPageView.as_view(), name= 'info_page'),
path('search_results', views.SearchResultsView.as_view(), name='search_results')
]

metrics/fusioncharts/fusioncharts-suite-xt/integrations/django/samples/fusioncharts/models.py
from __future__ import unicode_literals
from django.db import models

import json

# Create your models here.
class SalesRecord(models.Model):
	Region = models.CharField(max_length=100)
	Country = models.CharField(max_length=50)
	City = models.CharField(max_length=50)
	TotalSales = models.IntegerField()

	def __unicode__(self):
		return u'%s %s %s %s' % (self.Region, self.Country, self.City, self.TotalSales)

metrics/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

# Create your models here.
class ScholarProfile(models.Model):
	author_name= models.CharField(max_length=100)
	profile_url= models.URLField(max_length=200, primary_key= True)
	Company= models.CharField(max_length=100, null=True)
	Website= models.CharField(max_length=100, null=True)
	publication_title= ArrayField(models.CharField(max_length=500))
	normalized_citations= ArrayField(models.CharField(max_length=50), null= True)
	citations= ArrayField(models.CharField(max_length=50), null= True)
	coAuthors= ArrayField(models.CharField(max_length=50), null= True)
	created_at= models.DateTimeField(auto_now_add= True)
	country= models.CharField(max_length=100, null= True)
	publications= models.CharField(max_length=100, null= True)
	Tcitations= models.CharField(max_length=100, null= True)
	Hindex= models.CharField(max_length=100, null= True)
	Gindex= models.CharField(max_length=100, null= True)
	Mindex= models.CharField(max_length=100, null= True)
	TNCc= models.CharField(max_length=100, default= '00', )
	Year= ArrayField(models.CharField(max_length=100), null=True)
	
	def __str__(self):
		return (self.author_name)

metrics/forms.py
from django import forms
from .SCI import get_df

class IndexForm(forms.Form):
	scholar_url = forms.URLField(widget=forms.URLInput(
		attrs={
				'class': 'form-control',
				'placeholder': 'your google scholar profile url...',
		}
	))
	max_approx_publications = forms.IntegerField(widget=forms.TextInput(
		attrs={
			'class': 'form-control',
		}
	))

	df=get_df()
	Country_list= [tuple([x,x]) for x in df["Country"]]
	Country_list.sort()
	country = forms.CharField(widget=forms.Select(choices= Country_list,
		attrs={
				'class': 'form-control',
		}
	))																			#forms.Select(choices=Country_list)))

class SearchForm(forms.Form):
	search= forms.CharField(widget=forms.TextInput(
		attrs={
			'class': 'form-control',
			'placeholder': 'search for a scholar...'
		}
	)) 

	

metrics/fusioncharts/fusioncharts-suite-xt/integrations/django/samples/fusioncharts/views.py
from django.shortcuts import render

# it is a default view.
# please go to the samples folder for others view

def catalogue(request):
 	return  render(request, 'catalogue.html')

metrics/views.py
from django.shortcuts import render

from django.views.generic import TemplateView

from django.views.generic.list import ListView

from metrics.forms import IndexForm, SearchForm

from .scrap import Scraper

from django.http import HttpResponseRedirect

from django.urls import reverse

from .models import ScholarProfile

from .metrictables import NameTable

from django_tables2 import RequestConfig

from django_tables2.paginators import LazyPaginator

from .graphs import Graph

from django.db.models import Q 


class HomeView(TemplateView):
	template_name = 'metrics/home.html'
	

	def get(self, request):
		index_form = IndexForm
		search_form = SearchForm
	
		return render(request, self.template_name, {'indexform': index_form, 'searchform': search_form})

	def post(self, request):
		indexform = IndexForm(request.POST)
		if indexform.is_valid():
			text1 = indexform.cleaned_data['scholar_url']
			text2 = indexform.cleaned_data['max_approx_publications']
			text3 = indexform.cleaned_data['country']
			print(text1, text2, text3)
			z= Scraper(text1, text2, text3)
			key= z.getScholarData()
			

			return HttpResponseRedirect(reverse('metrics:results', args= (key,)))

class ResultView(ListView):
	model = ScholarProfile
	template_name= 'metrics/profile.html'
	paginate_by= 100
	
	def get(self, request, scholar_url):
		scholar_object= ScholarProfile.objects.get(profile_url= scholar_url)
		country= scholar_object.country
		company= scholar_object.Company
		website=scholar_object.Website
		t_publications= scholar_object.publications
		t_citations= scholar_object.Tcitations
		Year= scholar_object.Year
		g_index= scholar_object.Gindex
		h_index= scholar_object.Hindex
		m_index= scholar_object.Mindex
		tncc= scholar_object.TNCc
		publications= scholar_object.publication_title
		scholar_name= scholar_object.author_name
		search_form= SearchForm

		table= NameTable.createtable(publications, scholar_object.normalized_citations, scholar_object.citations, scholar_object.coAuthors, Year)

		table.paginate(page=request.GET.get('page', 1), per_page=100)
#RequestConfig(request, paginate={'paginator_class': LazyPaginator}).configure(table)				table.paginate(page=request.GET.get('page', 1), per_page=25)

		chartObj= Graph.histFusionchart(scholar_object.citations)

		img_url="https://scholar.google.com.au/citations?view_op=view_photo&user="+scholar_url+"&citpid=2"
		user= "url 'metrics:results' scholar_url={}".format(scholar_url)

		return (render (request, self.template_name, {'Name': scholar_name, 'user': scholar_url,
		 'list': publications, 'searchform': search_form, 'img_url': img_url, 'table': table, 
		 'company': company, 'website':website, 'Country': country, 'publications': t_publications, 
		 'Tcitations': t_citations, 'g_index': g_index, 'h_index': h_index, 'm_index': m_index, 'TNCc': tncc, 'output': chartObj.render()}))
		



class SearchResultsView(ListView):
    model = ScholarProfile
    template_name = 'metrics/search_results.html'

    def get_queryset(self): 
        query = self.request.GET.get('search')
        object_list = ScholarProfile.objects.filter(
            Q(author_name__icontains=query) #| Q(state__icontains=query)
        )
        return object_list



class InfoPageView(TemplateView):
	template_name= 'metrics/info.html'

	def get(self, request):
		return (render(request, self.template_name, {}))

metrics/templates/metrics/home.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
 	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
   <link rel="stylesheet" type="text/css" href="https://bootswatch.com/4/cyborg/bootstrap.min.css">
   <link href="https://fonts.googleapis.com/css?family=Sofia" rel='stylesheet'>
    {%load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'metrics/homedesign.css' %}">
	<title>Aossie Scholar</title>
</head>
	<body>
		<img id = "Alogo" src = "{% static 'metrics/images/AOSSIE_logo.png' %}" alt = "aossie_logo">
		<img id = "Slogo" src = "{% static 'metrics/images/Scholar_logo.png' %}" alt = "Scholar_logo">
		<img id = "index" src = "{% static 'metrics/images/index.png' %}" alt = "Index">
		<img id = "scholar" src = "{% static 'metrics/images/scholar.jpg' %}" alt = "Scholar">
		<img id = "cap" src= "{% static 'metrics/images/cap.png' %}" alt = "scholar cap">
		<p class="text-info">Scholars with a google Scholar profile, register here for better metrics...</p>

		
		<div class="container">

			<form method="post">

				{% csrf_token %}
				{{ indexform.errors }}
				<div id="index_form">
					{{ indexform.as_p }}
					<button type="submit" class="btn btn-outline-info">submit</button>
				</div>
			</form>
			
			<form action= "{% url 'metrics:search_results' %}" method= "get" class="form-inline my-2 my-lg-0">
				<!--{% csrf_token %} -->
				<!-- {{ searchform.errors }} -->
				<div id="search_form">
				<div class="active-purple-3 active-purple-4 mb-4">
				  <input class="form-control mr-sm-2"  
				  type="search" 
				  placeholder="Search" 
				  name="search"
				  value="{{ search_term }}"
				  aria-label="Search">
				</div>
				
				<button type="submit" class="btn btn-outline-success">Search</button>
				</div>
			</form>

		</div>

	</body>
	
</html>

metrics/templates/metrics/info.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>{{ Info }}</title>
	<meta charset="UTF-8">
 	<meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" type="text/css" href="https://bootswatch.com/4/flatly/bootstrap.min.css">
   <link href="https://fonts.googleapis.com/css?family=Rock Salt" rel='stylesheet'>
    {%load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'metrics/infodesign.css' %}">
	
</head>

<body>
	<div class="rect_up">
		<a class= "sign_in_text" href="{% url 'metrics:home' %}">Sign In</a>
		<img id = "Alogo" src = "{% static 'metrics/images/AOSSIE_logo.png' %}" alt = "aossie_logo">
		<img id = "Slogo" src = "{% static 'metrics/images/Scholar_logo.png' %}" alt="scholar_logo">
		<img id = "index" src = "{% static 'metrics/images/index.png' %}" alt = "Index">
	</div>
	<div class= "rect_head">
		<p id="general">General</p>
		<p id= "metric"> Metrics</p>
		<img id = "vector" src = "{% static 'metrics/images/vector.svg' %}" alt = "Vector">
		<p id="information"> Informarmation</p>
	</div>
	<div class= "def" id="hindex">
		<p id="h-index">h-index:</p><p id="defi">h-index is the largest number h such that h publications have at least h citations. </p>
	</div>
		<img id= "hgraphimg" src="{% static 'metrics/images/hgraph.png' %}" alt="h index">
		<img id="hindeximg" src="{% static 'metrics/images/hindex.png' %}" alt="h index">
	
	<div class= "def" id="mindex">
		<p id="m-index">m-index:</p><p id="defi">m-index is another variant of the h-index that displays h-index per year since first publication. The h-index tends to increase with career length, and m-index can be used in situations where this is a shortcoming, such as comparing researchers within a field but with very different career lengths. The m-index inherently assumes unbroken research activity since the first publication. </p>
		</div>
		<img id="mindeximg" src="{% static 'metrics/images/m-index.png' %}" alt="m index">
	
	<div class="def" id="gindex">
		<p id="g-index">g-index:</p><p id="defi">g-index is a variant of the h-index that, in its calculation, gives credit for the most highly cited papers in a data set. The g-index is always the same as or higher than the h-index.</p>
		</div>
		<img id="gindeximg" src="{% static 'metrics/images/g-index.png' %}" alt="g index">

	<div class="def" id="tnc">
		<p id="tn-c">TNC:</p><p id= "defi">TNC is the sum of "Ncitations" column from the profile, i.e., the sum of, citations recieved for a publication normalized by number of co-Author's worked for that publication.</p>
	</div>

	<div class="def" id="tncc">
		<p id="tnc-c">TNCc:</p><p id= "defi">Total Normalized Citations(TNCc) normalized per country. As the name suggests the metric is computed taking Author's country into consideration. We use "Citations per document" data as per source. The data can bee seen here <a href="https://www.scimagojr.com/countryrank.php">data</a></p>
		</div>
		<img id="tncimg" src="{% static 'metrics/images/TNC.jpeg' %}" alt="TNC">

	

</body>
</html>

	

metrics/templates/metrics/profile.html
<!DOCTYPE html>
<html lang="en">
{% load render_table from django_tables2 %}

<head>
	<title>{{ Name }}</title>
	<meta charset="UTF-8">
 	<meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" type="text/css" href="https://bootswatch.com/4/cosmo/bootstrap.min.css">
   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
   <link href="https://fonts.googleapis.com/css?family=Rock Salt" rel='stylesheet'>
    {%load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'metrics/profiledesign.css' %}">
    <script type="text/javascript" src="https://cdn.fusioncharts.com/fusioncharts/latest/fusioncharts.js"></script>
    <script type="text/javascript" src="https://cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.gammel.js"></script>
	
</head>
	<body>

		<div class= "rectangle-up">

			<div class="menu">
				<div class="btn-group dropright">
				  <button type="button" class="btn btn-secondary">
				   Menu
				  </button>
				  <button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				    <span class="sr-only">Toggle Dropright</span>
				  </button>
				  <div class="dropdown-menu">

				  	<a class= "dropdown-item" href="{% url 'metrics:home' %}">Sign In</a>
				    <a class="dropdown-item" href="./../../{{ user }}/results">Profile</a>
				    <a class="dropdown-item" href="{% url 'metrics:info_page' %}">Metrics info</a>
				  </div>
				</div>
			</div>

			

			<form action= "{% url 'metrics:search_results' %}" method= "get" class="form-inline my-2 my-lg-0">
				<!--{% csrf_token %} -->
				<!-- {{ searchform.errors }} -->
				<div id="search_form">
				<div class="active-purple-3 active-purple-4 mb-4">
				  <input class="form-control mr-sm-2"  
				  type="search" 
				  placeholder="Search" 
				  name="search"
				  value="{{ search_term }}"
				  aria-label="Search"></input>
				</div>
				<button id="search" type="submit" class="btn btn-outline-info">Search</button>
				</div>
			</form>

			<img id = "Alogo" src = "{% static 'metrics/images/AOSSIE_logo.png' %}" alt = "aossie_logo">
			<img id = "cap" src = "{% static 'metrics/images/cap.png' %}" alt = "Scholar_cap">
			<img id = "Slogo" src = "{% static 'metrics/images/Scholar_logo.png' %}" alt="scholar_logo">
			<!--<img id = "index" src = "{% static 'metrics/images/index.png' %}" alt = "Index">
			<img id = "scholar" src = "{% static 'metrics/images/scholar.jpg' %}" alt = "Scholar"> -->
		</div>
		

		
		<div>
			<img id="cap_up_scholar" src="{% static 'metrics/images/cap1.svg' %}" alt= "cap" />
		<img id="profile" src= "{{ img_url }}" alt="pic"/>
		<br>
		<h1 class="name"> {{ Name }}</h1>
		<p class= "info_rect_text" id= "company"> {{ company }}</p>
		<p class= "info_rect_text" id= "country">{{ Country }}</p>
		<div class= "info_rect">
			
			<a class=" info_rect_text" id= "website" href="{{ website }}">Website</a>
			<p class= "info_rect_text" id= "publications">Publications {{ publications }}</p>
			<p class= "info_rect_text" id= "tcitations">Citations {{ Tcitations }}</p>
			<a class= "info_rect_text" id= "TNCc" href= "{% url 'metrics:info_page' %}">TNCc {{ TNCc }}</a>

			<a class= "info_rect_text" id= "gindex" href="{% url 'metrics:info_page' %}">G-index {{ g_index }}</a>
			<a class= "info_rect_text" id= "hindex" href="{% url 'metrics:info_page' %}">h-index {{ h_index }}</a>
			<a class= "info_rect_text" id= "mindex" href="{% url 'metrics:info_page' %}">m-index {{ m_index }}</a>
		</div>

	</div>
	<div id="chart-1" class="chart">
    <!-- dumping JavaScript code here -->
    {{ output|safe }}

    </div>

	<div class="Table">
		{% render_table table %}
	</div>

	
	</body>

metrics/templates/metrics/search_results.html
<head>
	<meta charset="UTF-8">
 	<meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" type="text/css" href="https://bootswatch.com/4/sketchy/bootstrap.min.css">
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'metrics/searchdesign.css' %}">
	
</head>
<body>
	<h1>Search Results</h1>

		
			
		  {% for city in object_list %}
		  
		    
		    	<div class= "search_list">

		    		<a id="name" href="{{ city.profile_url }}/results">{{ city.author_name }}</a>
		    		<img id="profile" src= "https://scholar.google.com.au/citations?view_op=view_photo&user={{ city.profile_url }}&citpid=2" alt="pic"/>
		    		<br>
		    		<p id="company">{{ city.Company }}</p>
		    		<br><br>
		    		<a id= "personal" href="{{ city.Website }}">Personal</a>
				
				

				
		   
		   </div>
		   <br>
		  {% endfor %}
		   
		
	</body>